# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16edUPzKHxpvvtufL4ahkhPfKdYC2q7Yh
"""

!pip install wandb

import wandb

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras.datasets import mnist, fashion_mnist
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
import warnings
warnings.filterwarnings("ignore")
import seaborn as sns

ImageClasses = ["Pullover","Shirt","Coat","Trouser","Dress","Sandal","Bag","Sneaker","Ankle boot","T-shirt/top"]

from keras.datasets import fashion_mnist
(x_train,y_train),(x_test,y_test) = fashion_mnist.load_data()

wandb.init(project = "Assignment 1" ,name = "Question 1")

fig,axs = plt.subplots(2 , 5 , figsize = (20 , 6))
axs = axs.flatten()
class_images = []
for i in range(10):
  index = np.argmax(y_train == i)
  axs[i].imshow(x_train[index] , cmap = "gray")
  axs[i].set_title(ImageClasses[i])
  Image = wandb.Image(x_train[index] , caption = [ImageClasses[i]])
  class_images.append(Image)
wandb.log({"examples" : class_images})

